/**
 * 知识路线图节点 Hover 数据（网络开发工程师）
 * 来源：网络开发工程师.docx
 * type: 学习资源文字标签
 * match: SVG 命中关键词
 */
window.NODE_HOVER_DATA = {
  "汽车通信概论": {
    nodeName: "汽车通信概论",
    type: ["视频课", "直播课"],
    match: ["汽车通信概论"],
    description: "为所有网络开发工程的必备内容，在这部分内容中可以让学员从0开始认识网络，包括EE、ECU、MCU、总线等概念，夯实网络开发的基础。",
  },
  "ASR 通信": {
    nodeName: "ASR通信",
    type: ["视频课", "直播课"],
    match: ["ASR通信", "ASR 通信", "AUTOSAR通信", "AUTOSAR Communication"],
    description: "介绍在AUTOSAR CP架构下使用AUTOSAR组件进行不同应用层通信的机制。",
  },
  "CAN/CAN FD": {
    nodeName: "CAN/CAN FD",
    type: ["视频课", "直播课", "自学课", "内训课"],
    match: ["CAN&CANFD", "CAN&CAN FD", "CAN/CAN FD", "CAN/CANFD"],
    description: "学习车载网络最核心的 CAN/CAN FD 通信技术，掌握报文传输、仲裁机制、错误处理等关键知识。",
  },
  "CAN数据库": {
    nodeName: "CAN数据库",
    type: ["直播课", "内训课"],
    match: ["CAN数据库"],
    description: "涵盖多种工具处理和浏览不同类型数据库的功能、包括arxml、dbc等等",
  },
  "CANoe.CAN": {
    nodeName: "CANoe.CAN",
    type: ["视频课", "直播课", "公开课", "自学课", "内训课"],
    match: ["CANoe.CAN"],
    description: "重点介绍CANoe的分析和仿真功能，通过前面所学的理论与实操相结合，并采用实战演练等方式快速具备分析、调试和开发 CAN 网络的能力。",
  },
  "CAPL": {
    nodeName: "CAPL",
    type: ["视频课", "直播课", "内训课"],
    match: ["CAPL"],
    description: "系统学习 CAPL 脚本语言的语法、事件机制与报文处理逻辑，掌握 CANoe/CANalyzer 环境下的自动化开发能力。通过实战案例与脚本练习，提升网络仿真、测试与问题定位效率。",
  },
  "IL仿真": {
    nodeName: "交互层仿真",
    type: [],
    match: ["交互层仿真", "交互层Addon", "IL仿真", "IL Addon", "ILAddon"],
    description: "学习 CAN 交互层（Interaction Layer）仿真与 Addon 配置，掌握信号级通信仿真与残余总线搭建方法。",
  },
  "NM协议": {
    nodeName: "NM协议",
    type: [],
    match: ["NM协议"],
    description: "学习网络管理（Network Management）协议原理，掌握休眠/唤醒、节点监控与网络状态管理机制。",
  },
  "NM仿真": {
    nodeName: "NM仿真",
    type: [],
    match: ["NM仿真"],
    description: "在 CANoe 中实现 NM 网络管理仿真，掌握节点休眠唤醒流程验证与网络管理行为分析。",
  },
  "CAN 传输协议": {
    nodeName: "CAN传输协议",
    type: [],
    match: ["CAN传输协议", "CAN 传输协议", "CAN TP", "CANTP"],
    description: "学习 CAN 传输层协议（ISO-TP），掌握多帧分段传输、流控与数据重组，为诊断通信打下基础。",
  },
  "CAN诊断": {
    nodeName: "CAN诊断",
    type: [],
    match: ["CAN诊断"],
    description: "学习基于 CAN 的诊断通信，掌握 UDS 诊断服务流程、报文分析与常见诊断问题定位方法。",
  },
  "LIN协议": {
    nodeName: "LIN协议",
    type: ["视频课", "直播课", "自学课"],
    match: ["LIN协议"],
    description: "系统学习LIN（Local Interconnect Network）通信协议，掌握LIN网络架构、主从通信机制、帧结构、调度表以及节点管理等核心知识，理解LIN总线在车身电子控制系统中的应用场景。",
  },
  "LDF Explorer": {
    nodeName: "LDF Explorer",
    type: ["自学课"],
    match: ["LDFExplorer", "LDF Explorer", "LDF Explorer"],
    description: "重点介绍LIN Description File（LDF）文件的结构与配置方法，学习节点定义、信号描述、帧配置以及调度表管理等内容，掌握LIN网络数据库的创建、维护与工程化管理能力。",
  },
  "CANoe.LIN": {
    nodeName: "CANoe.LIN",
    type: ["视频课", "直播课", "公开课", "自学课", "内训课"],
    match: ["CANoe.LIN", "CAN.LIN"],
    description: "重点介绍CANoe平台中LIN网络的分析与仿真功能，通过理论结合实践的方式，掌握LIN网络搭建、报文监测、节点仿真、故障注入及通信分析等核心技能，快速具备LIN网络开发与调试能力。",
  },
  "LIN CAPL": {
    nodeName: "LIN CAPL",
    type: ["公开课", "自学课"],
    match: ["LINCAPL", "LIN CAPL"],
    description: "系统学习基于LIN网络的CAPL脚本开发技术，掌握事件机制、报文处理、节点模拟及自动化测试方法。通过实际案例训练，提升LIN网络仿真、自动化验证与问题定位效率。",
  },
  "LIN传输协议": {
    nodeName: "LIN传输协议",
    type: ["自学课"],
    match: ["LIN传输协议", "LIN TP", "LINTP"],
    description: "深入学习LIN Transport Protocol（LIN传输层协议），掌握长报文分段传输机制、数据重组流程以及与诊断服务的交互原理，为复杂诊断应用开发打下基础。",
  },
  "LIN诊断": {
    nodeName: "LIN诊断",
    type: ["自学课"],
    match: ["LIN诊断"],
    description: "系统学习LIN诊断通信机制，掌握诊断服务、故障码读取、节点配置、诊断流程分析及问题定位方法。通过实际案例掌握基于LIN网络的诊断开发与测试能力，满足车身电子系统开发需求",
  },
  "J1939协议": {
    nodeName: "J1939协议",
    type: ["视频课", "直播课", "自学课"],
    match: ["J1939协议"],
    description: "系统学习SAE J1939协议体系，掌握PGN、SPN、地址声明、请求响应机制、传输协议（TP）以及网络管理等核心内容，理解商用车网络通信架构与运行原理。",
  },
  "J1939数据库": {
    nodeName: "J1939数据库",
    type: ["公开课", "自学课"],
    match: ["J1939数据库"],
    description: "学习J1939数据库的架构，掌握DBC文件中PGN、SPN、信号映射及报文定义等内容，实现J1939网络数据的工程化管理与维护。",
  },
  "CANoe.J1939": {
    nodeName: "CANoe.J1939",
    type: ["公开课", "自学课", "内训课"],
    match: ["CANoe.J1939"],
    description: "重点介绍CANoe中J1939网络的分析与仿真功能，通过理论结合实践的方式，掌握J1939网络搭建、报文分析、节点仿真、故障排查及系统验证等关键技能。",
  },
  "J1939 CAPL": {
    nodeName: "J1939 CAPL",
    type: ["公开课", "自学课"],
    match: ["J1939CAPL", "J1939 CAPL"],
    description: "系统学习基于J1939协议的CAPL脚本开发技术，掌握PGN解析、地址声明模拟、节点行为仿真及自动化测试开发方法，通过实际案例提升开发与调试效率。",
  },
  "J1939交互层": {
    nodeName: "J1939交互层",
    type: ["自学课"],
    match: ["J1939交互层", "J1939 IL", "J1939IL"],
    description: "深入学习J1939 IL层传输协议（Transport Protocol），掌握BAM广播传输、RTS/CTS连接管理、多包数据传输等机制，了解DLL文件，并尝试使用其进行IL层设置。",
  },
  "ETH基础协议": {
    nodeName: "ETH基础协议",
    type: ["直播课", "自学课"],
    match: ["ETH基础协议", "Ethernet基础协议"],
    description: "在此站点，您将学习以太网基础协议的内容，内容包括以太网物理层、数据链路层（MAC地址和VLAN）、网络层（IPv4/IPv6）和传输层(TCP/UDP)。",
  },
  "ETH数据库": {
    nodeName: "ETH数据库",
    type: ["自学课"],
    match: ["ETH数据库", "Ethernet数据库"],
    description: "在测量分析以太网通信及搭建以太网残余总线仿真环境时，数据库是基础。在此站点，您将了解ARXML和FIBEX两种文件类型以及ARXML文件查看工具AUTOSAR Viewer。",
  },
  "VN硬件配置": {
    nodeName: "VN硬件配置",
    type: ["公开课", "自学课"],
    match: ["VN硬件配置"],
    description: "Vector Hardware Manager是Vector 的硬件配置工具。在此站点，您将学习VN5000系列硬件接口卡的配置，包括TAP、DC、Switch等。",
  },
  "CANoe.ETH": {
    nodeName: "CANoe.ETH",
    type: ["公开课", "自学课", "内训课"],
    match: ["CANoe.ETH", "CANoe.Ethernet"],
    description: "在此站点，您将学习在CANoe中搭建以太网工程，包括添加数据库、配置TCP/IP Stack、发送以太网数据包等。此外，您还将了解以太网相关的分析窗口如Protocol Monitor。",
  },
  "Ethernet CAPL": {
    nodeName: "ETH CAPL",
    type: ["公开课", "自学课", "内训课"],
    match: ["ETHCAPL", "ETH CAPL", "Ethernet CAPL", "EthernetCAPL"],
    description: "在此站点，您将学习以太网相关的CAPL，包括发送/访问以太网数据包、TCP Socket 编程以及UDP Socket 编程等。",
  },
  "PduMux": {
    nodeName: "PduMux",
    type: ["自学课"],
    match: ["PduMux", "PDU Multiplexing", "PDUMultiplexing"],
    description: "在此站点，您将学习PDU的概念及结构以及Container PDU的概念。",
  },
  "ETH IL": {
    nodeName: "ETH IL",
    type: ["自学课"],
    match: ["ETHIL", "ETH IL", "ETHIL"],
    description: "在此站点，您将学习应用CANoeILNL_AUTOSAR_ETH.DLL及AsrPDUIL2.DLL在以太网中实现基于信号的通信，并对通信数据进行分析。",
  },
  "SOME/IP协议": {
    nodeName: "SOME/IP协议",
    type: ["直播课", "公开课", "自学课", "内训课"],
    match: ["SOME/IP协议"],
    description: "SOME/IP通信协议允许以多种方式交换复杂的数据类型，例如RPC、Notification Event和Field。SOME/IP-SD协议用来建立通信。在此站点，您将学习SOME/IP和SOME/IP-SD协议。",
  },
  "SOME/IP仿真": {
    nodeName: "SOME/IP仿真",
    type: ["直播课", "公开课", "自学课", "内训课"],
    match: ["SOME/IP仿真"],
    description: "CANoe中SOME/IP的仿真功能基于SomeIP_IL.dll以及CANoeILNL_AUTOSAR_ETH.DLL实现。在此站点，你将学习如何应用上述DLL实现SOME/IP仿真。",
  },
  "TSN协议组": {
    nodeName: "TSN协议",
    type: ["自学课"],
    match: ["TSN协议", "TSN协议组", "TSN"],
    description: "TSN是一个庞大的协议组，在此站点，您将学习gPTP协议、AVTP协议。",
  },
  "AVB IL": {
    nodeName: "AVB IL",
    type: ["自学课"],
    match: ["AVBIL", "AVB IL", "AVB IL"],
    description: "在此站点，您将学习应用AVB_IL.DLL仿真gPTP协议、AVTP协议。",
  },
  "DoIP协议": {
    nodeName: "DoIP协议",
    type: ["直播课", "自学课", "内训课"],
    match: ["DoIP协议"],
    description: "在此站点，您将学习DoIP协议，包括DoIP诊断的流程和DoIP报文格式。",
  },
  "DoIP配置": {
    nodeName: "DoIP配置",
    type: ["直播课", "自学课", "内训课"],
    match: ["DolP配置", "DoIP配置"],
    description: "在此站点，您将学习如何正确配置 CANoe 以实现 DoIP 通信。",
  },
  "Security概论": {
    nodeName: "Security概论",
    type: ["直播课"],
    match: ["Securitv概论", "Security概论"],
    description: "在此站点，您将学习哈希算法、对称密钥、非对称密钥、MAC消息验证码、数字签名、证书、Diffie-Hellman密钥交换等密码技术，这是了解上层协议的基础。",
  },
  "Security协议": {
    nodeName: "Security协议",
    type: ["自学课"],
    match: ["Security协议"],
    description: "在此站点，您将学习SecOC、TLS等协议以及诊断安全相关的UDS服务。",
  },
  "CANoe.Security": {
    nodeName: "CANoe.Security",
    type: ["自学课"],
    match: ["CANoe.Security"],
    description: "Vector工具集成Security Manager插件，方便实现与OEM安全设施之间的链接。针对不同ECU的安全通信技术，均可通过通用化配置实现快速配置。在此站点，您将学习Security的相关配置。",
  },
};
