/**
 * 知识路线图目录
 */
window.ROADMAP_CATALOG = [
  {
    id: "diagnostic",
    title: "诊断工程师",
    titleEn: "DIAGNOSTIC ENGINEER",
    details: {
      role: "诊断开发",
      focus: "ECU诊断与故障分析",
      skills: "UDS · DTC · 故障分析 · 诊断服务 · ECU",
      mission: "发现问题，定位问题，解决问题",
    },
    watermark: "DIAG",
    heroImage: "素材/诊断工程师.png",
    avatarImage: "素材/诊断工程师小图.png",
    avatarVersion: 2,
    heroVersion: 3,
    homeOrder: 0,
    svgFile: "知识路线图 新ci 1-7.svg",
    dataKey: "NODE_HOVER_DATA_DIAGNOSTIC",
    pathCount: 6,
  },
  {
    id: "mbse",
    title: "MBSE系统设计工程师",
    titleEn: "MBSE SYSTEM DESIGN ENGINEER",
    details: {
      role: "系统设计",
      focus: "基于模型的系统工程",
      skills: "系统建模 · 架构设计 · 需求管理 · 需求追溯 · 协同设计",
      mission: "通过模型构建复杂系统",
    },
    watermark: "MBSE",
    heroImage: "素材/mbse系统设计工程师.png",
    avatarImage: "素材/MBSE系统设计工程师小图.png",
    heroVersion: 3,
    homeOrder: 1,
    svgFile: "知识路线图 新ci 1-3.svg",
    dataKey: "NODE_HOVER_DATA_MBSE",
    pathCount: 5,
  },
  {
    id: "soa",
    title: "SOA工程师",
    titleEn: "SOA ENGINEER",
    details: {
      role: "软件架构",
      focus: "面向服务的软件架构",
      skills: "服务设计 · 接口开发 · 服务通信 · 系统集成 · 架构设计",
      mission: "通过服务连接复杂系统",
    },
    watermark: "SOA",
    heroImage: "素材/soa工程师.png",
    avatarImage: "素材/soa工程师小图.png",
    heroVersion: 5,
    svgFile: "知识路线图 新ci 1-1.svg",
    dataKey: "NODE_HOVER_DATA_SOA",
    pathCount: 5,
  },
  {
    id: "calibration",
    title: "标定工程师",
    titleEn: "CALIBRATION ENGINEER",
    details: {
      role: "标定优化",
      focus: "车辆参数标定与性能优化",
      skills: "测量 · 标定 · 数据分析 · 参数优化 · 性能验证",
      mission: "让车辆性能达到最佳状态",
    },
    watermark: "CAL",
    heroImage: "素材/标定工程师.png",
    avatarImage: "素材/标定工程师小图.png",
    heroVersion: 3,
    homeOrder: 3,
    svgFile: "知识路线图 新ci 1-2.svg",
    dataKey: "NODE_HOVER_DATA_CALIBRATION",
    pathCount: 4,
  },
  {
    id: "network-dev",
    title: "网络开发工程师",
    titleEn: "NETWORK DEVELOPMENT ENGINEER",
    details: {
      role: "网络开发",
      focus: "汽车网络与通信架构",
      skills: "CAN · 以太网 · 通信协议 · ECU · 网络设计",
      mission: "构建可靠的整车通信网络",
    },
    watermark: "NET DEV",
    heroImage: "素材/网络开发工程师.png",
    avatarImage: "素材/网络开发工程师小图.png",
    avatarVersion: 3,
    heroVersion: 3,
    homeOrder: 4,
    svgFile: "知识路线图 新ci 1-5.svg",
    dataKey: "NODE_HOVER_DATA",
    pathCount: 10,
  },
  {
    id: "network-test",
    title: "网络测试工程师",
    titleEn: "NETWORK TEST ENGINEER",
    details: {
      role: "测试验证",
      focus: "ECU 与网络全链路测试",
      skills: "测试用例 · SIL/HIL · 通信测试 · 故障注入 · 功能验证",
      mission: "验证系统功能与通信可靠性",
    },
    watermark: "NET TEST",
    heroImage: "素材/网络测试工程师.png",
    avatarImage: "素材/网络测试工程师小图.png",
    avatarVersion: 2,
    heroVersion: 3,
    homeOrder: 5,
    svgFile: "知识路线图 新ci 1-4.svg",
    dataKey: "NODE_HOVER_DATA_NETWORK_TEST",
    pathCount: 12,
  },
  {
    id: "embedded",
    title: "嵌入式软件开发工程师",
    titleEn: "EMBEDDED SOFTWARE DEVELOPMENT ENGINEER",
    details: {
      role: "软件开发",
      focus: "ECU嵌入式软件开发",
      skills: "C/C++ · AUTOSAR · ECU · 软件调试 · 系统集成",
      mission: "开发驱动智能汽车的核心软件",
    },
    watermark: "EMBED",
    heroImage: "素材/嵌入式软件开发工程师.png",
    avatarImage: "素材/嵌入式开发工程师小图.png",
    heroVersion: 3,
    homeOrder: 6,
    svgFile: "知识路线图 新ci 1-6.svg",
    dataKey: "NODE_HOVER_DATA_EMBEDDED",
    pathCount: 11,
  },
];
