/**
 * 知识路线图目录
 */
window.ROADMAP_CATALOG = [
  {
    id: "diagnostic",
    title: "诊断工程师",
    titleEn: "DIAGNOSTIC ENGINEER",
    watermark: "DIAG",
    heroImage: "素材/诊断工程师.png",
    avatarImage: "素材/诊断工程师小图.png",
    avatarVersion: 2,
    homeOrder: 0,
    svgFile: "知识路线图 新ci 1-7.svg",
    dataKey: "NODE_HOVER_DATA_DIAGNOSTIC",
  },
  {
    id: "mbse",
    title: "MBSE系统设计工程师",
    titleEn: "MBSE SYSTEM DESIGN ENGINEER",
    watermark: "MBSE",
    heroImage: "素材/mbse系统设计工程师.png",
    avatarImage: "素材/MBSE系统设计工程师小图.png",
    homeOrder: 1,
    svgFile: "知识路线图 新ci 1-3.svg",
    dataKey: "NODE_HOVER_DATA_MBSE",
  },
  {
    id: "soa",
    title: "SOA工程师",
    titleEn: "SOA ENGINEER",
    watermark: "SOA",
    heroImage: "素材/soa工程师.png",
    avatarImage: "素材/soa工程师小图.png",
    heroVersion: 2,
    homeOrder: 2,
    svgFile: "知识路线图 新ci 1-1.svg",
    dataKey: "NODE_HOVER_DATA_SOA",
  },
  {
    id: "calibration",
    title: "标定工程师",
    titleEn: "CALIBRATION ENGINEER",
    watermark: "CAL",
    heroImage: "素材/标定工程师.png",
    avatarImage: "素材/标定工程师小图.png",
    homeOrder: 3,
    svgFile: "知识路线图 新ci 1-2.svg",
    dataKey: "NODE_HOVER_DATA_CALIBRATION",
  },
  {
    id: "network-dev",
    title: "网络开发工程师",
    titleEn: "NETWORK DEVELOPMENT ENGINEER",
    watermark: "NET DEV",
    heroImage: "素材/网络开发工程师.png",
    avatarImage: "素材/网络开发工程师小图.png",
    homeOrder: 4,
    svgFile: "知识路线图 新ci 1-5.svg",
    dataKey: "NODE_HOVER_DATA",
  },
  {
    id: "network-test",
    title: "网络测试工程师",
    titleEn: "NETWORK TEST ENGINEER",
    watermark: "NET TEST",
    heroImage: "素材/网络测试工程师.png",
    avatarImage: "素材/网络测试工程师小图.png",
    avatarVersion: 2,
    homeOrder: 5,
    svgFile: "知识路线图 新ci 1-4.svg",
    dataKey: "NODE_HOVER_DATA_NETWORK_TEST",
  },
  {
    id: "embedded",
    title: "嵌入式软件开发工程师",
    titleEn: "EMBEDDED SOFTWARE DEVELOPMENT ENGINEER",
    watermark: "EMBED",
    heroImage: "素材/嵌入式软件开发工程师.png",
    avatarImage: "素材/嵌入式开发工程师小图.png",
    homeOrder: 6,
    svgFile: "知识路线图 新ci 1-6.svg",
    dataKey: "NODE_HOVER_DATA_EMBEDDED",
  },
];
